
export const SIGNUPUSER = 'SIGNUPUSER'
export const CURRENTUSER = 'CURRENTUSER'
export const SHOPCATOGERY = 'SHOPCATOGERY'
export const SHOPSUBCATOGERY = 'SHOPSUBCATOGERY'
export const ISLOADER = 'ISLOADER'
export const ISERROR = 'ISERROR'

